# -*- coding: utf-8 -*-
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(558, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setTextFormat(QtCore.Qt.AutoText)
        self.label1.setObjectName("label1")
        self.horizontalLayout.addWidget(self.label1)
        self.le1 = QtWidgets.QLineEdit(self.centralwidget)
        self.le1.setObjectName("le1")
        self.horizontalLayout.addWidget(self.le1)
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.b1.clicked.connect(self.findprice)
        self.horizontalLayout.addWidget(self.b1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.le2 = QtWidgets.QLineEdit(self.centralwidget)
        self.le2.setObjectName("le2")
        self.horizontalLayout_3.addWidget(self.le2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.le3 = QtWidgets.QLineEdit(self.centralwidget)
        self.le3.setObjectName("le3")
        self.horizontalLayout_2.addWidget(self.le3)
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.b2.clicked.connect(self.findtotal)   #connect
        self.horizontalLayout_2.addWidget(self.b2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.le4 = QtWidgets.QLineEdit(self.centralwidget)
        self.le4.setObjectName("le4")
        self.horizontalLayout_4.addWidget(self.le4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 27))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Bookstore"))
        self.label1.setText(_translate("mainWindow", "Book Title :"))
        self.b1.setText(_translate("mainWindow", "Find Price"))
        self.label_2.setText(_translate("mainWindow", "Price :"))
        self.label_5.setText(_translate("mainWindow", "Quantity :"))
        self.b2.setText(_translate("mainWindow", "Find Total"))
        self.label_4.setText(_translate("mainWindow", "Total :"))

    def findprice(self):
        import sqlite3

        booklib=sqlite3.connect("Booklib.db")     #connects to a book library database
        book=booklib.cursor()

        t=self.le1.text()

        book.execute('''SELECT * from books WHERE title==?''',(t,))
        mybook=book.fetchone()
           
        if mybook!=None:

               print(mybook)
               self.pr=mybook[3]
               self.le2.setText(str(self.pr))
        else:
               print ("Title Not Found")
    
    def findtotal(self):
        self.qty=float(self.le3.text())
        total=self.pr*self.qty
        self.le4.setText(str(total))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
